### PR TITLE
Allow selecting both a user and an organization

### PR DESCRIPTION
**Pull request by schweikart**
Removed the restriction to add topics/labels to user OR organization repositories exclusively.

### CODE REVIEW

**Comment by Zelgius** [comment]
Can you rebase this?

**Review by Zelgius — CHANGES_REQUESTED** [review]
Can you rebase this against the codebase please?

**Comment by schweikart** [comment]
I've rebased the PR and tested everything again. Let me know if I need to do any other changes :)

**Review by Zelgius — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
