### PR TITLE
Disallow forks and private by default, but allow by flags

### PR DESCRIPTION
**Pull request by halkeye**
so related to #9 

Type allows different values depending on which version of docs you look
at. So Simplified the checks to just be able to exclude anything you don't
want.

I could default excludeForks to true, but then to disable it you'd have to use --no-excludeForks which isn't documented by --help

Let me know

### CODE REVIEW

**Comment by Zelgius** [comment]
I think excluding forks is the way to go. If you just add the option then it'll be documented by --help automatically. I can update the README afterwards. I'm pretty sure being able to limit it to just public, non-fork non-archives (which someone already did) will be what a vast majority of people using the tool will want.

**Comment by Zelgius** [comment]
Ok. After thinking about it let's default the tool to just do public repos. Instead of doing an exclude could we do --include-forks --include-private so these can be regular flags and then we'll document in the readme a --no-include-public that will serve if you want to remove the public option (I feel this will be a very low use case)

**Comment by halkeye** [comment]
I havn't fully tested this as I don't want to start messing with labels everwhere and making it dry run is a bit of effort, but I can do more extensive testing tonight.

Might want to enable ignore whitespace to review this

* Switched exclude => include and deleted the non forks and public options
* Added a shared logger statement so every log line has repo name
* Bail out of archived and disabled early (which is why so many whitespace lines changed)

**Comment by halkeye** [comment]
Okay tested by adding a dryrun, looks good

**Review by Zelgius — APPROVED** [review]
This looks awesome! Thanks!

**Pull request merged**
