### PR TITLE
Addition and multiplication 

### PR DESCRIPTION
**Pull request by Daksheshapkare**
The code words upon addition and multiplication of two number inputed by uset
here is the code 
Number1= int(input("Enter 1st your number =")) 
Number2=  int(input("Enter 2nd your number =")) 
Multiply= Number1*Number2
print("Multiplied number is =" , Multiply) 
Add=Number1+Number2
print("Added number is =", Add)

### CODE REVIEW

**Comment by Daksheshapkare** [comment]
Please merge this

**Comment by MattIPv4** [comment]
No, your PR was closed as it was spammy. You are adding unrelated code to a project. Please review the rules and values of Hacktoberfest, and understand that Hacktoberfest is about making valuable contributions to open source projects, not spamming random code in random projects.

**Comment by Daksheshapkare** [comment]
> No, your PR was closed as it was spammy. You are adding unrelated code to a project. Please review the rules and values of Hacktoberfest, and understand that Hacktoberfest is about making valuable contributions to open source projects, not spamming random code in random projects.

So what type of code you want so u can merge it

**Comment by MattIPv4** [comment]
You can take a look at the open issues to see what contributions this project is looking for currently.

**Pull request closed without merging**
